# Generated by Django 4.2.7 on 2023-11-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد شده')),
                ('content', models.TextField(verbose_name='متن')),
                ('discription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده ')),
            ],
        ),
    ]
