# Generated by Django 4.2.7 on 2023-11-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
