# Generated by Django 4.2.7 on 2023-11-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=75, verbose_name='پست الکترونیکی')),
                ('message', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog.blog', verbose_name='نطرات')),
            ],
            options={
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
