# Generated by Django 5.0.6 on 2024-06-05 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='سيوی  سایت')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='انتشار')),
            ],
            options={
                'verbose_name_plural': 'دسته بندیها',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان لاتین')),
                ('publish_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'verbose_name_plural': 'تگها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد شده')),
                ('content', models.TextField(verbose_name='متن')),
                ('discription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='سؤی وبگاه')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='عکسها')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='blog.category', verbose_name='دسته بندی')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='blog.tags', verbose_name='تگها')),
            ],
            options={
                'verbose_name_plural': 'بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, verbose_name='پست الکترونیکی')),
                ('message', models.TextField(verbose_name='نظر')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name=' مقاله مربوطه ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام')),
            ],
            options={
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
