# Generated by Django 5.0.6 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('imgae', models.ImageField(upload_to='image/food/% Y/% m/% d/')),
                ('price', models.PositiveIntegerField()),
                ('discription', models.TextField()),
                ('rate', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
