# Generated by Django 5.0.6 on 2024-05-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='end_time',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='start_time',
            new_name='time',
        ),
    ]
