# Generated by Django 5.0.6 on 2024-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_end_time_food_pub_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
