# Generated by Django 5.0.6 on 2024-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0003_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image/food/%Y/%m/%d/')),
                ('price', models.PositiveIntegerField()),
                ('discription', models.TextField()),
                ('rate', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'غذا',
                'ordering': ['-pub_date'],
            },
        ),
    ]
