# Generated by Django 5.0.6 on 2024-05-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
