# Generated by Django 5.0.6 on 2024-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoryfood',
            options={'verbose_name_plural': '  دسته بندی غدا '},
        ),
    ]
