# Generated by Django 5.0.6 on 2024-06-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_suggestionform_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionform',
            options={'verbose_name_plural': ' پیشنهادات  '},
        ),
    ]
